@echo off
echo Starting QR Code Generator with Google Lens Compatibility...
cd /d "C:\Users\Nagineni Dhanush\Music\Desktop\games\project-bolt-sb1-lpjqkecx\project"
echo Installing dependencies...
npm install
echo Starting development server...
npm run dev
pause